### ISSUE TITLE
Post 2: Grouped and stacked bars

### ISSUE THREAD

**Issue by pavithraes** [bokeh/dataviz-fundamentals#3]
**Topics to cover:** Grouped and stacked bar plots

**Link to WIP blog post:** (https://docs.google.com/document/d/17X5aWqkB9FvZHICdPxuTCBfXrbidU25H9_2JuFdXz3c/edit)

**Checklist:**

Tasks:

- [x] Notebook created
- [x]  Blog post created
- [x]  Notebook rendered on GitHub pages
- [x]  Blog post published
- [x]  Social media announcements

Checks:

- [x]  Is the notebook reproducible?
- [x]  Does the notebook text and blog post text follow our docs style guide?
- [x]  Do all images have alt-text?

**Comment by Azaya89** [comment]
Since these plots are going under PR #19 that will resolve Issue #6, maybe we can close this one?

**Comment by pavithraes** [comment]
@Azaya89 Indeed, thanks!
