### ISSUE TITLE
Introduction post.

### ISSUE THREAD

**Issue by Azaya89** [bokeh/dataviz-fundamentals#5]
- [x]  Introduction blog post submitted on Medium
- [x] README file updated with the current Table of Contents (WIP) 
- [x] Index page created on the GH page with links in the Table of contents
- [x] Introduction plot made and linked in the GH page
- [x] Blog post published on Medium

**Comment by bryevdv** [comment]
ref: https://blog.bokeh.org/welcome-to-outreachy-week-1-16ad6803f0c4

Thanks @Azaya89
